# Generated by Django 4.1.5 on 2023-06-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=254)),
                ("Password", models.CharField(max_length=50)),
                ("Address", models.TextField()),
            ],
        ),
    ]
