# Generated by Django 4.1.5 on 2023-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Stu_Reg", models.CharField(max_length=50)),
                ("Stu_Name", models.CharField(max_length=50)),
                ("Stu_email", models.EmailField(max_length=254)),
                ("Stu_password", models.CharField(max_length=50)),
                ("Stu_Number", models.CharField(max_length=50)),
            ],
        ),
    ]
